[filename]

# You can define your own custom pattern to be used for naming the image files.
# Available parameters are:
# date: The time the image was created using the Bing Image Creator. The date uses ISO-8601 formatting.
# index: The order the image was placed in the collection. Right pads 4 zeroes. e.g. 0001 or 0012.
# prompt: The prompt that was used to create the image.
# sep: A seperator that may be used between parameters.
#
# The default file name would look like this: "2023-11-11T1512Z_0133_a-cute-cat".
# If the width is smaller than 1024 pixels, a "_T" for thumbnail will be added.
filename_pattern = "$date$sep$index$sep$prompt"
# Uses your local time zone to format the filename. Set to false to use UTC.
use_local_time_zone = true

[collection]

# You can define if you want to only download specific collections or from all collections.
# Leave the array empty to download all entries.
# Also use "Saved Images" for the default collection and not your localization.
# To include specific collections add the title to the array.
# For example for a collection called `Bing AI images` add the entry "Bing AI images".
collections_to_include = []

[collection.delete_collection_after_download]
# This setting is used to toggle the deletion setting below. It doesn't do anything on its own.
# To use any method below set this to true.
toggle = false

# Sets the delete mode. Available options are:
# - safest:
    # Will delete the collection after downloading the images, but only if **all** images were downloaded successfully.
    # Will not delete the collection if 1000 images were returned by the collection API,
    # because it's not known whether the collection is complete or not.
# - safeish:
    # Same as safest, but delete the collection if all non downloaded images have the reason "Not found" i.e. 404.
    # This means that all images that were actually still on Microsoft's servers were downloaded.
# - dangerous:
    # Will delete the collection after downloading the images, regardless whether all images were downloaded or not.
mode = "safest"

[image_source]
# The image source to use.
# Available options are:
# - api: Uses the collection API to gather image data. Limited to 1000 images.
# - file: Uses the images_clipboard.txt file to gather image data. Does not contain same thumbnail data as Collection API.
method = "file"

[detail_api]
# Because the detail API does not always return valid values, it's retried the specified amount of times.
max_attempts = 5

[debug]

# Enables additional debug statements and debug functionality.
debug = false
# Enables logging the console output to a file.
use_log_file = true
# The filename of the log file.
debug_filename = "bing_image_creator.log"
# Displays more detailed statistics at the end of the program.
detailed_statistics = false
